# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git repository
          uses: actions/checkout@v2
        - name: Compile LaTeX document
          uses: xu-cheng/texlive-action/full@v1
          with:
            run: |
              pdflatex LibrettoCantiParrocchia.tex
              texlua songidx.lua cbtitle.sxd cbtitle.sbx
              texlua songidx.lua cbtitle2.sxd cbtitle2.sbx
              pdflatex LibrettoCantiParrocchia.tex
        - name: Archive Pdf Document
          uses: actions/upload-artifact@v2
          with:
            name: LibrettoCantiParrocchia
            path: LibrettoCantiParrocchia.pdf
